version: '3.8'

services:
  backend_development:  # Renaming 'server' to 'backend'
    build:
      context: ./cms  # Changed context to 'backend'
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-serverrr
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./cms/:/usr/src/app  # Changed path to 'backend'
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo_developement
    env_file: ./cms/.env  # Changed path to 'backend'
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  mongo_developement:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  frontend_developement:  # Renaming 'client' to 'frontend'
    build:
      context: ./uicms  # Changed context to 'frontend'
      dockerfile: Dockerfile
    image: react-app
    container_name: myapp-react-clientt
    command: npm start
    volumes:
      - ./uicms/:/usr/app  # Changed path to 'frontend'
      - /usr/app/node_modules
    depends_on:
      - backend_development  # Changed from ['server'] to 'backend'
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
